# Generated by Django 6.0.3 on 2026-03-26 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('batch_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('filename', models.CharField(default='', max_length=255)),
                ('row_count', models.IntegerField(default=0)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('address_key', models.CharField(db_index=True, default='', max_length=255)),
                ('parcel_id', models.CharField(db_index=True, default='', max_length=20)),
                ('buyer_name', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('organization', models.CharField(blank=True, default='', max_length=255)),
                ('program', models.CharField(db_index=True, default='', max_length=50)),
                ('closing_date', models.CharField(default='', max_length=20)),
                ('commitment', models.TextField(default='')),
                ('purchase_type', models.CharField(blank=True, default='', max_length=50)),
                ('compliance_1st_attempt', models.CharField(blank=True, default='', max_length=50)),
                ('compliance_2nd_attempt', models.CharField(blank=True, default='', max_length=50)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('formatted_address', models.TextField(default='')),
                ('geocoded_at', models.DateTimeField(blank=True, null=True)),
                ('streetview_path', models.CharField(default='', max_length=500)),
                ('streetview_date', models.CharField(default='', max_length=20)),
                ('streetview_available', models.BooleanField(default=False)),
                ('streetview_historical_path', models.CharField(default='', max_length=500)),
                ('streetview_historical_date', models.CharField(default='', max_length=20)),
                ('historical_imagery_checked_at', models.DateTimeField(blank=True, null=True)),
                ('satellite_path', models.CharField(default='', max_length=500)),
                ('imagery_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('detection_score', models.FloatField(blank=True, null=True)),
                ('detection_label', models.CharField(db_index=True, default='', max_length=30)),
                ('detection_details', models.JSONField(blank=True, default=dict)),
                ('detection_ran_at', models.DateTimeField(blank=True, null=True)),
                ('finding', models.CharField(db_index=True, default='', max_length=30)),
                ('notes', models.TextField(default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.CharField(default='staff', max_length=100)),
                ('compliance_status', models.CharField(choices=[('compliant', 'Compliant'), ('in_progress', 'In Progress'), ('needs_outreach', 'Needs Outreach'), ('non_compliant', 'Non-Compliant'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=20)),
                ('tax_status', models.CharField(choices=[('current', 'Current'), ('delinquent', 'Delinquent'), ('payment_plan', 'Payment Plan'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('last_tax_payment', models.DateField(blank=True, null=True)),
                ('tax_amount_owed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('homeowner_exemption', models.BooleanField(default=False)),
                ('outreach_attempts', models.PositiveIntegerField(default=0)),
                ('last_outreach_date', models.DateField(blank=True, null=True)),
                ('last_outreach_method', models.CharField(blank=True, default='', max_length=20)),
                ('regrid_condition', models.CharField(blank=True, default='', max_length=100)),
                ('portal_survey_date', models.DateField(blank=True, null=True)),
                ('import_batch', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['finding', 'detection_label'], name='tracker_pro_finding_980226_idx'), models.Index(fields=['compliance_status'], name='tracker_pro_complia_c98cfa_idx'), models.Index(fields=['buyer_name'], name='tracker_pro_buyer_n_5a2e95_idx')],
            },
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('mail', 'Mail'), ('site_visit', 'Site Visit'), ('text', 'Text')], max_length=20)),
                ('direction', models.CharField(default='outbound', max_length=20)),
                ('date_sent', models.DateField(blank=True, null=True)),
                ('subject', models.CharField(default='', max_length=255)),
                ('body', models.TextField(default='')),
                ('response_received', models.BooleanField(default=False)),
                ('response_date', models.DateField(blank=True, null=True)),
                ('response_notes', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='tracker.property')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
