# Generated by Django 6.0.3 on 2026-05-13 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_postgis_photo_evidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('program_keys', models.JSONField(blank=True, default=list)),
                ('variants', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('retired', 'Retired')], db_index=True, default='draft', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('cadence', models.CharField(blank=True, default='', max_length=50)),
                ('schedule', models.JSONField(blank=True, default=list)),
                ('grace_days', models.PositiveIntegerField(default=0)),
                ('required_uploads', models.JSONField(blank=True, default=list)),
                ('required_docs', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.AddField(
            model_name='communication',
            name='action',
            field=models.CharField(blank=True, db_index=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='communication',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communication',
            name='body_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='communication',
            name='provider_message_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='communication',
            name='recipient_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='communication',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communication',
            name='status',
            field=models.CharField(choices=[('logged', 'Logged'), ('draft', 'Draft'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('bounced', 'Bounced'), ('failed', 'Failed')], db_index=True, default='logged', max_length=20),
        ),
        migrations.AddField(
            model_name='communication',
            name='template_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_index=True, default='', max_length=255)),
                ('email', models.EmailField(blank=True, db_index=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('organization', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('status', models.CharField(db_index=True, default='unknown', max_length=30)),
                ('flags', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['full_name', 'organization', 'id'],
                'indexes': [models.Index(fields=['full_name', 'organization'], name='tracker_buy_full_na_1d4f56_idx')],
            },
        ),
        migrations.AddField(
            model_name='communication',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to='tracker.buyer'),
        ),
        migrations.AddField(
            model_name='property',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='tracker.buyer'),
        ),
        migrations.AddField(
            model_name='communication',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to='tracker.emailtemplate'),
        ),
        migrations.AddField(
            model_name='property',
            name='program_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='tracker.program'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('storage_key', models.CharField(blank=True, default='', max_length=500)),
                ('storage_url', models.URLField(blank=True, default='')),
                ('mime_type', models.CharField(blank=True, default='', max_length=120)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(db_index=True, default='document', max_length=50)),
                ('slot', models.CharField(blank=True, default='', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('communication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='tracker.communication')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='tracker.property')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['property', 'category'], name='tracker_doc_propert_f0f61a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, default='staff', max_length=100)),
                ('category', models.CharField(db_index=True, default='general', max_length=50)),
                ('body', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_notes', to='tracker.buyer')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_notes', to='tracker.property')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['property', '-created_at'], name='tracker_not_propert_74dff9_idx')],
            },
        ),
        migrations.CreateModel(
            name='ActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('NOT_DUE_YET', 'Not Due Yet'), ('ATTEMPT_1', 'First Attempt'), ('ATTEMPT_2', 'Second Attempt'), ('WARNING', 'Warning'), ('DEFAULT_NOTICE', 'Default Notice'), ('TAX_VERIFICATION', 'Tax Verification'), ('MISSING_EMAIL', 'Missing Email'), ('NEEDS_INSPECTION', 'Needs Inspection'), ('MANUAL_REVIEW', 'Manual Review')], db_index=True, max_length=40)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('dismissed', 'Dismissed')], db_index=True, default='open', max_length=20)),
                ('due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('days_overdue', models.IntegerField(default=0)),
                ('enforcement_level', models.PositiveSmallIntegerField(default=0)),
                ('priority', models.IntegerField(db_index=True, default=0)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(blank=True, default='system', max_length=50)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='tracker.property')),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_items', to='tracker.buyer')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_items', to='tracker.program')),
            ],
            options={
                'ordering': ['status', '-priority', 'due_date', 'id'],
                'indexes': [models.Index(fields=['status', 'action', 'due_date'], name='tracker_act_status_57df8d_idx'), models.Index(fields=['property', 'status'], name='tracker_act_propert_2363a8_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaxSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('current', 'Current'), ('delinquent', 'Delinquent'), ('payment_plan', 'Payment Plan'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('checked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('source', models.CharField(blank=True, default='manual', max_length=50)),
                ('tax_year', models.CharField(blank=True, default='', max_length=20)),
                ('amount_owed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_snapshots', to='tracker.property')),
            ],
            options={
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['property', '-checked_at'], name='tracker_tax_propert_b9e47b_idx'), models.Index(fields=['status'], name='tracker_tax_status_5ce07f_idx')],
            },
        ),
    ]
