# Generated by Django 5.2.15 on 2026-06-05 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_workflow_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(default='', max_length=120)),
                ('kind', models.CharField(default='arcgis', max_length=30)),
                ('base_url', models.URLField(blank=True, default='')),
                ('layer_id', models.CharField(blank=True, default='', max_length=20)),
                ('field_map', models.JSONField(blank=True, default=dict)),
                ('edit_date_field', models.CharField(blank=True, default='', max_length=80)),
                ('object_id_field', models.CharField(blank=True, default='OBJECTID', max_length=80)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_cursor', models.CharField(blank=True, default='', max_length=120)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.AddField(
            model_name='property',
            name='assessed_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='boundary_geojson',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='forfeiture_status',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='forfeiture_status_year',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='property',
            name='land_use',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='property',
            name='owner_of_record',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='property_class',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='property',
            name='taxable_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ParcelValueSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_id', models.CharField(db_index=True, max_length=20)),
                ('assessed_value', models.FloatField(blank=True, null=True)),
                ('taxable_value', models.FloatField(blank=True, null=True)),
                ('forfeiture_status', models.CharField(blank=True, default='', max_length=20)),
                ('source', models.CharField(default='county_arcgis', max_length=40)),
                ('observed_at', models.DateField()),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='value_snapshots', to='tracker.property')),
            ],
            options={
                'ordering': ['-observed_at'],
                'indexes': [models.Index(fields=['parcel_id', 'observed_at'], name='tracker_par_parcel__fdb739_idx')],
                'unique_together': {('parcel_id', 'observed_at', 'source')},
            },
        ),
        migrations.CreateModel(
            name='ServiceLineRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_id', models.CharField(db_index=True, default='', max_length=20)),
                ('address', models.TextField(default='')),
                ('material', models.CharField(blank=True, default='', max_length=60)),
                ('verified_date', models.DateField(blank=True, null=True)),
                ('replacement_status', models.CharField(blank=True, default='', max_length=60)),
                ('source', models.CharField(default='flintpipemap', max_length=50)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_lines', to='tracker.property')),
            ],
            options={
                'indexes': [models.Index(fields=['parcel_id'], name='tracker_ser_parcel__3556ac_idx')],
            },
        ),
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='running', max_length=20)),
                ('fetched', models.PositiveIntegerField(default=0)),
                ('matched', models.PositiveIntegerField(default=0)),
                ('updated', models.PositiveIntegerField(default=0)),
                ('unmatched', models.PositiveIntegerField(default=0)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='tracker.datasource')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['source', '-started_at'], name='tracker_syn_source__b799b9_idx')],
            },
        ),
    ]
