# Generated by Django 5.2.15 on 2026-06-05 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_datasource_property_assessed_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeighborhoodContextScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_id', models.CharField(db_index=True, max_length=20)),
                ('neighborhood_def', models.CharField(max_length=20)),
                ('signal', models.CharField(max_length=40)),
                ('parcel_value', models.FloatField(blank=True, null=True)),
                ('local_mean', models.FloatField(blank=True, null=True)),
                ('local_std', models.FloatField(blank=True, null=True)),
                ('z_score', models.FloatField(blank=True, null=True)),
                ('spatial_lag', models.FloatField(blank=True, null=True)),
                ('moran_cluster', models.CharField(default='NS', max_length=2)),
                ('moran_p', models.FloatField(blank=True, null=True)),
                ('gi_star', models.FloatField(blank=True, null=True)),
                ('neighbor_parcel_ids', models.JSONField(blank=True, default=list)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='context_scores', to='tracker.property')),
            ],
            options={
                'indexes': [models.Index(fields=['parcel_id', 'neighborhood_def', 'signal'], name='tracker_nei_parcel__d47eba_idx')],
                'unique_together': {('parcel_id', 'neighborhood_def', 'signal')},
            },
        ),
    ]
