# Generated by Codex on 2026-06-24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0006_compliancecase_caseevent_benchmark_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TwentySyncRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tenant_id", models.CharField(db_index=True, default="gclba", max_length=50)),
                ("object_name", models.CharField(db_index=True, max_length=80)),
                ("external_key", models.CharField(db_index=True, max_length=160)),
                ("twenty_record_id", models.CharField(blank=True, db_index=True, default="", max_length=120)),
                ("twenty_url", models.URLField(blank=True, default="")),
                ("payload_hash", models.CharField(blank=True, default="", max_length=64)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("last_webhook_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("action_item", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="twenty_sync_records", to="tracker.actionitem")),
                ("communication", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="twenty_sync_records", to="tracker.communication")),
                ("property", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="twenty_sync_records", to="tracker.property")),
            ],
            options={
                "ordering": ["object_name", "external_key"],
            },
        ),
        migrations.CreateModel(
            name="TwentyWebhookEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event", models.CharField(db_index=True, max_length=120)),
                ("object_name", models.CharField(blank=True, db_index=True, default="", max_length=80)),
                ("twenty_record_id", models.CharField(blank=True, db_index=True, default="", max_length=120)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("processed", models.BooleanField(db_index=True, default=False)),
                ("error", models.TextField(blank=True, default="")),
                ("received_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-received_at"],
            },
        ),
        migrations.AddIndex(
            model_name="twentysyncrecord",
            index=models.Index(fields=["tenant_id", "object_name"], name="tracker_twe_tenant__f9fb20_idx"),
        ),
        migrations.AddIndex(
            model_name="twentysyncrecord",
            index=models.Index(fields=["twenty_record_id"], name="tracker_twe_twenty__42c188_idx"),
        ),
        migrations.AddConstraint(
            model_name="twentysyncrecord",
            constraint=models.UniqueConstraint(fields=("tenant_id", "object_name", "external_key"), name="unique_twenty_sync_record"),
        ),
        migrations.AddIndex(
            model_name="twentywebhookevent",
            index=models.Index(fields=["event", "-received_at"], name="tracker_twe_event_beb689_idx"),
        ),
        migrations.AddIndex(
            model_name="twentywebhookevent",
            index=models.Index(fields=["object_name", "twenty_record_id"], name="tracker_twe_object__498d68_idx"),
        ),
    ]
