# Generated by Django 5.2.15 on 2026-07-07 20:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_twenty_crm_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='sources',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='SourceConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_id', models.CharField(db_index=True, max_length=20)),
                ('external_key', models.CharField(blank=True, db_index=True, default='', max_length=160)),
                ('source', models.CharField(db_index=True, default='gclba-index', max_length=80)),
                ('kind', models.CharField(choices=[('owner_mismatch', 'Owner mismatch'), ('reverse_mismatch', 'Reverse mismatch'), ('pid_orphan', 'Parcel orphan'), ('condition_regression', 'Condition regression'), ('value_disagreement', 'Value disagreement')], db_index=True, max_length=40)),
                ('severity', models.CharField(choices=[('watch', 'Watch'), ('review', 'Review'), ('high', 'High')], db_index=True, default='review', max_length=20)),
                ('title', models.CharField(max_length=240)),
                ('plain_language', models.TextField(blank=True, default='')),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('observed_at', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], db_index=True, default='open', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_conflicts', to='tracker.property')),
            ],
            options={
                'ordering': ['-observed_at', 'parcel_id', 'kind'],
            },
        ),
        migrations.CreateModel(
            name='CandidateProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_id', models.CharField(db_index=True, max_length=20)),
                ('external_key', models.CharField(blank=True, db_index=True, default='', max_length=160)),
                ('address', models.TextField(blank=True, default='')),
                ('reason', models.TextField()),
                ('evidence', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('imported', 'Imported'), ('dismissed', 'Dismissed')], db_index=True, default='queued', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_properties', to='tracker.property')),
                ('source_conflict', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_properties', to='tracker.sourceconflict')),
            ],
            options={
                'ordering': ['status', 'parcel_id', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='sourceconflict',
            index=models.Index(fields=['status', 'kind'], name='tracker_sou_status_80158e_idx'),
        ),
        migrations.AddIndex(
            model_name='sourceconflict',
            index=models.Index(fields=['source', 'external_key'], name='tracker_sou_source_9e0b28_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateproperty',
            index=models.Index(fields=['status', 'parcel_id'], name='tracker_can_status_db06dc_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateproperty',
            index=models.Index(fields=['external_key'], name='tracker_can_externa_3501ad_idx'),
        ),
    ]
