# Generated by Django 5.2.15 on 2026-07-31 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_property_sources_sourceconflict_candidateproperty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyImageEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_source', models.CharField(choices=[('STREET_VIEW', 'Street View'), ('HISTORICAL_STREET_VIEW', 'Historical Street View'), ('SATELLITE', 'Satellite'), ('NAIP_AERIAL', 'NAIP aerial'), ('MAPILLARY', 'Mapillary'), ('SURVEY_ARCHIVE', 'Survey archive'), ('BUYER_SUBMITTED', 'Buyer submitted'), ('STAFF_UPLOAD', 'Staff upload'), ('OTHER', 'Other')], db_index=True, max_length=40)),
                ('image_kind', models.CharField(choices=[('EXTERIOR', 'Exterior'), ('HISTORICAL_EXTERIOR', 'Historical exterior'), ('AERIAL', 'Aerial'), ('BEFORE', 'Before'), ('AFTER', 'After'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=30)),
                ('capture_date', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('capture_date_precision', models.CharField(blank=True, choices=[('DAY', 'Day'), ('MONTH', 'Month'), ('YEAR', 'Year')], default='', max_length=10)),
                ('storage_key', models.CharField(blank=True, db_index=True, default='', max_length=500)),
                ('sha256', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('pano_id', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('source_license', models.CharField(blank=True, choices=[('PUBLIC_DOMAIN', 'Public domain'), ('CC_BY_SA', 'CC BY-SA'), ('ORG_OWNED', 'Organization owned'), ('LICENSED_DISPLAY_ONLY', 'Licensed display only')], default='', max_length=40)),
                ('footprint_meters', models.FloatField(blank=True, null=True)),
                ('heading_degrees', models.FloatField(blank=True, null=True)),
                ('pitch_degrees', models.FloatField(blank=True, null=True)),
                ('field_of_view', models.FloatField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, default='')),
                ('thumbnail_url', models.TextField(blank=True, default='')),
                ('attribution', models.CharField(blank=True, default='', max_length=255)),
                ('provider_record_id', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_evidence', to='tracker.property')),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='tracker.propertyimageevidence')),
            ],
            options={
                'ordering': ['property_id', 'capture_date', 'id'],
                'indexes': [models.Index(fields=['property', 'image_source', 'capture_date'], name='tracker_pro_propert_22d111_idx'), models.Index(fields=['property', 'pano_id'], name='tracker_pro_propert_1cb34d_idx'), models.Index(fields=['sha256'], name='tracker_pro_sha256_252546_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('capture_date__gt', ''), models.Q(('image_source', 'HISTORICAL_STREET_VIEW'), _negated=True)), fields=('property', 'image_source', 'capture_date'), name='unique_owned_image_evidence_by_date'), models.UniqueConstraint(condition=models.Q(('pano_id__gt', ''), ('image_source__in', ['STREET_VIEW', 'HISTORICAL_STREET_VIEW'])), fields=('property', 'image_source', 'pano_id'), name='unique_licensed_image_evidence_by_pano')],
            },
        ),
    ]
